title: "Chukwudi Odimegwu"
description: "Business Analyst | Data Engineer | MSc Business Analytics"
url: "https://ChuksOdis.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache

author:
  name: "Chukwudi Odimegwu"
  bio: "Business Analyst | Data Engineer | Strategy & Growth Modelling"
  location: "Scotland, United Kingdom"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Chuks3774"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/yourprofile"
