title: "Chukwudi Odimegwu"
description: "Data Engineer | Business Analyst"
url: "https://Chuks3774.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Chukwudi Odimegwu"
  bio: "Data Engineer | Business Analyst | Strategy & Growth Modelling"
  location: "Scotland, United Kingdom"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Chuks3774"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/www.linkedin.com/in/chuks-odis-902662261"
