title: "Chukwudi Odimegwu"
description: "Business Analyst | Data Engineer | MSc Business Analytics"
url: "https://Chuks3774.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

